markdown: maruku
markdown_ext: markdown,mkd,mkdn,md
pygments: true
permalink:  /:title
auto: true
rdiscount:
  extensions:[smart, Kramdown]
paginate: 1
paginate_path: "/page:num"
name: Chris Schuld
url: chris.shahariaazam.com
description: Chris Schuld's Blog
twitter: shaharia
github: shahariaazam
facebook: shaharia.azam
author: Chris Schuld
mainSiteHome: 'http://chris.shahariaazam.com'